### PR TITLE
Official Docker image

### LINKED ISSUE #273: Official Docker image?
I'm finding several Docker images for Coturn available, but it is hard to tell if one is official or at least recommended.

Would it make sense to have a Docker section in the main README that points to official or recommended Docker images? I believe this would greatly improve the adoption of this. 

Thanks!

### PR DESCRIPTION
**Pull request by tyranron**
Fixes #273, instrumentisto/coturn-docker-image#25, instrumentisto/coturn-docker-image#24,  instrumentisto/coturn-docker-image#40

## Features

- [x] building from local sources (for `edge` tag and local development)
- [x] building from from Git ref (for versions) 
- [x] allow non-root use using privileged ports (instrumentisto/coturn-docker-image#40)
- [x] run as non-root by default
- [x] `alpine` image
- [x] `debian` image
- [x] multi-arch support
- [x] migrate image's [Bats](https://github.com/bats-core/bats-core) tests
- [x] support revisions and stable tags in versioning
- [x] image's CHANGELOG
- [x] GitHub Actions pipeline for building, testing and publishing
    - [x] publishing to DockerHub
    - [x] publishing to GitHub Container Registry
    - [x] publishing to Quay.io
    - [x] releasing to GitHub
- [x] detailed README
- [x] Contribution Guide

Prometheus support is beyond this PR's scope and will be added in a separate PR.

### CODE REVIEW

**Comment by tyranron** [comment]
@misi I see you've [switched to custom compilation of `mongo-c-driver` of more newer version](https://github.com/coturn/coturn/commit/33aa2e6ec5f55f3b3bde49f000055a9d6d436dfd) than Debian packages have. Would you be so kind to clarify a reason?

**Comment by misi** [comment]
It was because of an external Pull Request. 
We can split to have a special docker image for the debian version mongo driver and other for the most up2date version of mongo..
AFAIU debian is not up2date with latest mongodb version. Any proposal?

**Comment by tyranron** [comment]
@misi I think we can just drop debian package and compile it from sources for a while, until the next stable debian version will contain a fresher package.

Anyway, this shouldn't impose any friction, as we will need to compile Prometheus libs in a similar manner, in a near future.

**Comment by tyranron** [comment]
@misi okay, we're almost there. Everything seems to work fine and well, and it's only question about documentation and polishing (yes, `docker/` directory, I'm looking at you and you redundant custom images).

But at this step I need you to make some preparations with container registries, so we will be able to publish images onto them via GitHub Actions.

I advise to use 3 registries simultaneously to publish the image:
- [Docker Hub](https://hub.docker.com/): the most famous and the most weird due to too strict pull rate limits.
- [GitHub Container Registry](https://github.com/orgs/coturn/packages): just GitHub and has no limits.
- [Quay.io](https://quay.io/): has free security scanning.

The setup described below we need to do only once, and then GitHub Actions CI pipeline will do all the stuff automatically, without any hassle for us.

### Docker Hub

You need an account with [`Admin` privileges](https://hub.docker.com/repository/docker/coturn/coturn/permissions) to use in GitHub Actions. You may use your own, or better create a `coturn-bot` account on Docker Hub. After this is done, specify either in [organization secrets][1], or in [project repository secrets][2], its login and password as `DOCKERHUB_BOT_USER` and `DOCKERHUB_BOT_PASS` (__exactly__ like that).

Also, from [Docker Hub build settings page](https://hub.docker.com/repository/docker/coturn/coturn/builds/edit) remove all the build rules, set all the radio buttons to `Off` and click `Save`. GitHub Actions will take care about all the buids by itself.

### Quay.io

On Quay.io you first need to register, then create a `coturn` organization. After this is done, [create a new repository](https://quay.io/new/) (use `Public` and `(Empty repository)` radio buttons).

Now, we need to [create a robot account](https://quay.io/organization/coturn?tab=robots) (the link will work after organization is created) and give `Admin` permissions to `coturn` repository. After doing that, click on a gizmo and select a `View credentials` item in dropdown list. Specify thos credentials as `QUAYIO_ROBOT_USERNAME` and `QUAYIO_ROBOT_TOKEN` either in [organization secrets][1], or in [project repository secrets][2].

This is, however, not everything. For being able to automatically update README on Quay.io via GitHub Actions, we need yet another token for that. Go to [OAuth applications page](https://quay.io/organization/coturn?tab=applications) and create a new one with name `GitHub Actions`. Then, open its settings and specify `Homepage URL: https://github.com/coturn`, `Description: GitHub Actions Integration`, `Redirect/Callback URL Prefix: https://github.com/coturn`. Then switch to `Generate Token` tab of this page in left menu and generate a new token with `Administer Repositories` right only. Use it as `QUAYIO_API_TOKEN` either in [organization secrets][1], or in [project repository secrets][2].

### GitHub Container Registry

Phew... 😅

Create a [PAT token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) for the `coturn` GitHub organization with rights to manage repos and push to packages. And the specify it as `GCR_BOT_PAT` either in [organization secrets][1], or in [project repository secrets][2].

------------------------

After all this done, and after merging this PR once its ready, the current `master` branch will be built and pushed to all the container registries with auto-updating the `README`. So, this way we will check that everything is fine.


[1]: https://github.com/organizations/coturn/settings/secrets/actions
[2]: https://github.com/coturn/coturn/settings/secrets/actions

**Comment by misi** [comment]
All done we have the secrets now.

**Comment by misi** [comment]
Many  thanks for you hard work! It is highly appreciated!

**Comment by tyranron** [comment]
@misi I've described the logic of CI workflow and manual actions required to produce a new release of Docker image in a Contribution Guide.

As you've added me to project contributors, after merging this PR, please, request my review in any PRs related to the Docker image, if by some reasons I won't react to them by myself. So, this way, I'll try to continue maintaing the high quality of the image.

**Comment by j1elo** [comment]
Very nice addition! This comment https://github.com/coturn/coturn/pull/746#issuecomment-814978430 is almost worth for a blog post :-)

I'm making a mental note here for waiting until this is merged and then proposing the improved public IP detection from here: https://github.com/instrumentisto/coturn-docker-image/pull/41

**Comment by misi** [comment]
@tyranron Huge thanks!
Sorry for my late merge..

**Comment by misi** [comment]
@tyranron I will ask your review any related change of course! Many Thanks again..

**Comment by namazso** [comment]
the build seems to be failing: https://github.com/coturn/coturn/runs/2346953593

**Comment by misi** [comment]
@namazso  Yes I know, and I am trying to figure out why.. @tyranron Any idea?
It is strange auth works fine.. As you can see also in the logs
I could push out with the same credential an image..

I read here that out of disk space could cause this error:
https://github.com/docker/build-push-action/issues/238
Maybe disk is full?

>@crazy-max I believe out of disk space is causing this and opened an issue with GitHub to clarify and I just got confirmation that there's ~14 GB of disk space available and 7GB of RAM on the hosted runners at GitHub. I think Travis CI.org offers about 40-50 GB on their runners (but lesser of build time, simultaneous builds quotas).
>
>With regards to the awesome actions for cache, qemu, buildx etc, would it be possible to consider an enhancement with regards to the error message, which is a bit vague.
>
>Perhaps in case of OOM or OOD, the message "rpc error: code = Unknown desc = unexpected status: 403 Forbidden" could be "Out of disk space or RAM", if it is possible to capture this error condition?

**Comment by crazy-max** [comment]
@misi Don't think that's an issue with disk space but permissions scope for `ghcr.io/coturn/coturn` with `GCR_BOT_PAT` secret. I think you should use the [GITHUB_TOKEN](https://docs.github.com/en/actions/reference/authentication-in-a-workflow). See https://github.com/docker/login-action#github-container-registry

**Comment by misi** [comment]
@crazy-max I also thought it but I made test and if I use the same GCR_BOT_PAT I could push out an image to github registry.
But thanks I will try to double check it again.

**Comment by tyranron** [comment]
@misi yup, something is wrong with scopes of `GCR_BOT_PAT` secret. 

Here is the info about required scopes:
https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry

Using `GITHUB_TOKEN` seems to be even the better way, but I've never tried it. Will try in my repos and write about it here.

**Comment by tyranron** [comment]
@misi ok, it seems that `GITHUB_TOKEN` works perfectly well, but requires some manual preparations:

1. Authenticate to `ghcr.io` locally for beint able to push:
    ```bash
    docker login ghcr.io
    ```

2. Create a repository on `ghcr.io` by pushing the image:
    ```bash
    docker pull coturn/coturn:4.5.2
    docker tag coturn/coturn:4.5.2 ghcr.io/coturn/coturn:4.5.2
    docker push ghcr.io/coturn/coturn:4.5.2
    ```

3. Go to the [package settings](https://github.com/orgs/coturn/packages/container/coturn/settings) and use `Change package visibility` option to make the package public.

4. Go to the [`Actions access` tab](https://github.com/orgs/coturn/packages/container/coturn/settings/actions_access), click `Add repository` button and type `coturn` to select its repository. Once its added, change its rights to `Write` instead of default `Read`.

Once its done, click `Re-run all jobs` button on [latest build](https://github.com/coturn/coturn/actions/runs/750936256).

The `GCR_BOT_PAT` secret may be fully removed.

**Comment by misi** [comment]
Thanks for the guide. I changed everything accordingly. 

This setting was also missing:
https://docs.github.com/packages/getting-started-with-github-container-registry/enabling-improved-container-support

**Comment by misi** [comment]
Seems it works fine now! :)

@tyranron  HUGE THANKS!!

(The GCR_BOT_PAT secret may has been removed)

**Pull request merged**
