### PR TITLE
Adding a encryption logic for the password of MySQL DB user.

### PR DESCRIPTION
**Pull request by mustafabingul**
Co-authored-by: Erdem Duman <erdemduman23@gmail.com>
Co-authored-by: mashary <mashar.yazici@gmail.com>

### CODE REVIEW

**Comment by misi** [comment]
Many Thanks!
I could check it on Monday. 
Sorry for the delay..

**Comment by misi** [comment]
Unfortunately I have to move it to Tomorrow.. 
Sorry..

**Comment by misi** [comment]
I can't comiple, and there are many warnings about unused variables etc.
So IMHO this code quality not yet reached that level that is required.
It should be more solid..

**Comment by misi** [comment]
Could you please continue work on it?

**Comment by mustafabingul** [comment]
Yes, I know that there are many warnings and unused variables. Okay, I will fix them.
However, we could compile the project. What kind of error did you get when you tried to compile it?

**Comment by misi** [comment]
You have to avoid any unused and redundant code or any other warning.
So improve the code..
Structure your source code to encode in only one function. etc.

Here is my long long problem list.
```
src/apps/relay/mainrelay.c:155:1: warning: missing initializer for field ‘secret_key_file’ of ‘turn_params_t {aka struct _turn_params_}’ [-Wmissing-field-initializers]
 };
 ^
In file included from src/apps/relay/mainrelay.c:31:0:
src/apps/relay/mainrelay.h:318:8: note: ‘secret_key_file’ declared here
   char secret_key_file[1025];
        ^~~~~~~~~~~~~~~
src/apps/relay/mainrelay.c:942:5: warning: no previous prototype for ‘init_ctr’ [-Wmissing-prototypes]
 int init_ctr(struct ctr_state *state, const unsigned char iv[8]){
     ^~~~~~~~
src/apps/relay/mainrelay.c: In function ‘base64encode’:
src/apps/relay/mainrelay.c:962:27: warning: pointer targets in return differ in signedness [-Wpointer-sign]
  return (*mem_bio_mem_ptr).data; //Returns base-64 encoded data. (See: "buf_mem_st" struct).
         ~~~~~~~~~~~~~~~~~~^~~~~
src/apps/relay/mainrelay.c: In function ‘encrypt’:
src/apps/relay/mainrelay.c:972:22: warning: pointer targets in passing argument 1 of ‘AES_set_encrypt_key’ differ in signedness [-Wpointer-sign]
  AES_set_encrypt_key(mykey, 128, &key);
                      ^~~~~
In file included from src/apps/relay/mainrelay.h:81:0,
                 from src/apps/relay/mainrelay.c:31:
/usr/include/openssl/aes.h:43:5: note: expected ‘const unsigned char *’ but argument is of type ‘char *’
 int AES_set_encrypt_key(const unsigned char *userKey, const int bits,
     ^~~~~~~~~~~~~~~~~~~
src/apps/relay/mainrelay.c:977:20: warning: pointer targets in passing argument 2 of ‘init_ctr’ differ in signedness [-Wpointer-sign]
   init_ctr(&state, iv);
                    ^~
src/apps/relay/mainrelay.c:942:5: note: expected ‘const unsigned char *’ but argument is of type ‘char *’
 int init_ctr(struct ctr_state *state, const unsigned char iv[8]){
     ^~~~~~~~
src/apps/relay/mainrelay.c:981:3: warning: implicit declaration of function ‘AES_ctr128_encrypt’; did you mean ‘AES_cfb128_encrypt’? [-Wimplicit-function-declaration]
   AES_ctr128_encrypt(tempinput, out, strlen(tempinput), &key, state.ivec, state.ecount, &state.num);
   ^~~~~~~~~~~~~~~~~~
   AES_cfb128_encrypt
src/apps/relay/mainrelay.c:981:3: warning: nested extern declaration of ‘AES_ctr128_encrypt’ [-Wnested-externs]
src/apps/relay/mainrelay.c:983:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (j = 0;  j< strlen(tempinput); j++) {
                       ^
src/apps/relay/mainrelay.c: In function ‘generate_aes_128_key’:
src/apps/relay/mainrelay.c:1003:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < sizeof(key); i++) {
                ^
src/apps/relay/mainrelay.c: In function ‘base64decode’:
src/apps/relay/mainrelay.c:1040:9: warning: pointer targets in return differ in signedness [-Wpointer-sign]
  return base64_decoded;        //Returns base-64 decoded data with trailing null terminator.
         ^~~~~~~~~~~~~~
src/apps/relay/mainrelay.c: In function ‘decodedTextSize’:
src/apps/relay/mainrelay.c:1045:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < strlen(input); ++i) {
                   ^
src/apps/relay/mainrelay.c: In function ‘decrypt’:
src/apps/relay/mainrelay.c:1061:25: warning: pointer targets in passing argument 1 of ‘AES_set_encrypt_key’ differ in signedness [-Wpointer-sign]
     AES_set_encrypt_key(mykey, 128, &key);
                         ^~~~~
In file included from src/apps/relay/mainrelay.h:81:0,
                 from src/apps/relay/mainrelay.c:31:
/usr/include/openssl/aes.h:43:5: note: expected ‘const unsigned char *’ but argument is of type ‘char *’
 int AES_set_encrypt_key(const unsigned char *userKey, const int bits,
     ^~~~~~~~~~~~~~~~~~~
src/apps/relay/mainrelay.c:1065:27: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
     char *encryptedText = base64decode(in, bytes_to_decode); //changed
                           ^~~~~~~~~~~~
src/apps/relay/mainrelay.c:1069:22: warning: pointer targets in passing argument 2 of ‘init_ctr’ differ in signedness [-Wpointer-sign]
     init_ctr(&state, iv);
                      ^~
src/apps/relay/mainrelay.c:942:5: note: expected ‘const unsigned char *’ but argument is of type ‘char *’
 int init_ctr(struct ctr_state *state, const unsigned char iv[8]){
     ^~~~~~~~
src/apps/relay/mainrelay.c:1068:9: warning: unused variable ‘i’ [-Wunused-variable]
     int i=0;
         ^
src/apps/relay/mainrelay.c:1066:10: warning: unused variable ‘temp’ [-Wunused-variable]
     char temp[256];
          ^~~~
src/apps/relay/mainrelay.c:1062:9: warning: unused variable ‘size’ [-Wunused-variable]
     int size=0;
         ^~~~
src/apps/relay/mainrelay.c:1057:19: warning: unused variable ‘loop_count’ [-Wunused-variable]
     int remainder,loop_count;
                   ^~~~~~~~~~
src/apps/relay/mainrelay.c:1057:9: warning: unused variable ‘remainder’ [-Wunused-variable]
     int remainder,loop_count;
         ^~~~~~~~~
src/apps/relay/mainrelay.c:1056:13: warning: unused variable ‘k’ [-Wunused-variable]
     int j=0,k=0;
             ^
src/apps/relay/mainrelay.c:1056:9: warning: unused variable ‘j’ [-Wunused-variable]
     int j=0,k=0;
         ^
src/apps/relay/mainrelay.c: In function ‘adminmain’:
src/apps/relay/mainrelay.c:1815:13: warning: pointer targets in passing argument 1 of ‘encrypt’ differ in signedness [-Wpointer-sign]
     encrypt((unsigned char*)pwd, generated_key);
             ^
src/apps/relay/mainrelay.c:964:6: note: expected ‘char *’ but argument is of type ‘unsigned char *’
 void encrypt(char* in, char* mykey){
      ^~~~~~~
src/apps/relay/mainrelay.c:1658:7: warning: unused variable ‘ch’ [-Wunused-variable]
  char ch;
       ^~
src/apps/relay/mainrelay.c:1657:6: warning: unused variable ‘counter’ [-Wunused-variable]
  int counter;
      ^~~~~~~
src/apps/relay/mainrelay.c: In function ‘init_ctr’:
src/apps/relay/mainrelay.c:947:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/apps/relay/dbdrivers/dbd_mysql.c:87:7: warning: no previous prototype for ‘decryptPassword’ [-Wmissing-prototypes]
 char* decryptPassword(char* in, char* mykey){
       ^~~~~~~~~~~~~~~
src/apps/relay/dbdrivers/dbd_mysql.c: In function ‘decryptPassword’:
src/apps/relay/dbdrivers/dbd_mysql.c:95:22: warning: pointer targets in passing argument 1 of ‘AES_set_encrypt_key’ differ in signedness [-Wpointer-sign]
  AES_set_encrypt_key(mykey, 128, &key);
                      ^~~~~
In file included from src/apps/relay/dbdrivers/../mainrelay.h:81:0,
                 from src/apps/relay/dbdrivers/dbd_mysql.c:32:
/usr/include/openssl/aes.h:43:5: note: expected ‘const unsigned char *’ but argument is of type ‘char *’
 int AES_set_encrypt_key(const unsigned char *userKey, const int bits,
     ^~~~~~~~~~~~~~~~~~~
src/apps/relay/dbdrivers/dbd_mysql.c:99:24: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
  char *encryptedText = base64decode(in, bytes_to_decode); //changed
                        ^~~~~~~~~~~~
src/apps/relay/dbdrivers/dbd_mysql.c:103:2: warning: implicit declaration of function ‘init_ctr’; did you mean ‘inet_neta’? [-Wimplicit-function-declaration]
  init_ctr(&state, iv);
  ^~~~~~~~
  inet_neta
src/apps/relay/dbdrivers/dbd_mysql.c:103:2: warning: nested extern declaration of ‘init_ctr’ [-Wnested-externs]
src/apps/relay/dbdrivers/dbd_mysql.c:105:2: warning: implicit declaration of function ‘AES_ctr128_encrypt’; did you mean ‘AES_cfb128_encrypt’? [-Wimplicit-function-declaration]
  AES_ctr128_encrypt(encryptedText, outdata, newTotalSize, &key, state.ivec, state.ecount, &state.num);
  ^~~~~~~~~~~~~~~~~~
  AES_cfb128_encrypt
src/apps/relay/dbdrivers/dbd_mysql.c:105:2: warning: nested extern declaration of ‘AES_ctr128_encrypt’ [-Wnested-externs]
src/apps/relay/dbdrivers/dbd_mysql.c:102:6: warning: unused variable ‘i’ [-Wunused-variable]
  int i=0;
      ^
src/apps/relay/dbdrivers/dbd_mysql.c:100:7: warning: unused variable ‘temp’ [-Wunused-variable]
  char temp[256];
       ^~~~
src/apps/relay/dbdrivers/dbd_mysql.c:96:6: warning: unused variable ‘size’ [-Wunused-variable]
  int size=0;
      ^~~~
src/apps/relay/dbdrivers/dbd_mysql.c:91:16: warning: unused variable ‘loop_count’ [-Wunused-variable]
  int remainder,loop_count;
                ^~~~~~~~~~
src/apps/relay/dbdrivers/dbd_mysql.c:91:6: warning: unused variable ‘remainder’ [-Wunused-variable]
  int remainder,loop_count;
      ^~~~~~~~~
src/apps/relay/dbdrivers/dbd_mysql.c:90:10: warning: unused variable ‘k’ [-Wunused-variable]
  int j=0,k=0;
          ^
src/apps/relay/dbdrivers/dbd_mysql.c:90:6: warning: unused variable ‘j’ [-Wunused-variable]
  int j=0,k=0;
      ^
/tmp/ccQeUsf7.o: In function `encrypt':
/home/misi/work/coturn/src/apps/relay/mainrelay.c:981: undefined reference to `AES_ctr128_encrypt'
/tmp/ccQeUsf7.o: In function `decrypt':
/home/misi/work/coturn/src/apps/relay/mainrelay.c:1071: undefined reference to `AES_ctr128_encrypt'
/tmp/ccLHhxWN.o: In function `decryptPassword':
/home/misi/work/coturn/src/apps/relay/dbdrivers/dbd_mysql.c:105: undefined reference to `AES_ctr128_encrypt'
collect2: error: ld returned 1 exit status
Makefile:134: recipe for target 'bin/turnserver' failed
make: *** [bin/turnserver] Error 1
```

**Comment by misi** [comment]
May check this: https://wiki.openssl.org/index.php/EVP_Symmetric_Encryption_and_Decryption

**Comment by misi** [comment]
I guess it is connected that I use Ubuntu LTS and so OpenSSL version: 1.1.0g  2 Nov 2017

**Comment by mustafabingul** [comment]
We are going to fix warnings and coding structure as soon as possible but we are too busy to implement another encryption - decryption algorithm, actually.

We will also test it in Ubuntu LTS, "Red Hat Enterprise Linux Server" was our testing environment.

**Comment by mustafabingul** [comment]
For now, could you add this pull request?

**Comment by misi** [comment]
In openssl 1.1 AES_ctr128_encrypt renamed...

So please add this:
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
		CRYPTO_ctr128_encrypt(...
#else
		AES_ctr128_encrypt(...
#endif

**Comment by misi** [comment]
> For now, could you accept this pull request?
Actually I could merge it to a new developer branch, but not yet to master..

**Comment by mustafabingul** [comment]
Where should I add it?

**Comment by misi** [comment]
I think you should add everywhere where you use AES_ctr128_encrypt function is.

**Comment by mustafabingul** [comment]
Again, could you check it?

**Comment by erdemduman** [comment]
Hello there, I am one of the coders of this pull request. We are really busy to fix warnings (Only 4 warnings appear in our compiler) right now.
Could you please accept this pull request for now? We assure you to fix them as soon as possible.

**Comment by misi** [comment]
Please be little bit more patient. I am testing it...
See branch: https://github.com/coturn/coturn/tree/mysql-password-encryption
I don't have any warning actually :-)

But I need still some time.
I do my best...

Sorry for the inconvenience..

**Comment by misi** [comment]
There is some problem on Mac OS X with the change..
https://travis-ci.org/coturn/coturn/builds/416337371

See:
https://travis-ci.org/coturn/coturn/branches

**Comment by misi** [comment]
See my changes: https://github.com/coturn/coturn/tree/mysql-password-encryption
I will continue tomorrow..

**Pull request merged**
