### PR TITLE
Reformat code

### PR DESCRIPTION
**Pull request by eakraly**
Reformat to address linter error

### CODE REVIEW

**Review by jonesmz — APPROVED** [review]

**Comment by jonesmz** [comment]
To get this working, you can configure another apt repository from llvm

https://apt.llvm.org/

Jammy (22.04) LTS - Last update : Sat, 10 Aug 2024 17:19:55 UTC / Revision: 20240810053640+0c783be98549

deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main
deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy main
# 18
deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main
deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main
# 19
deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main
deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main

**Comment by eakraly** [comment]
Not sure what is the best path forward here
I'm on mac and using homebrew - so llvm (and clang-format) just get updated...
I suppose to lock in on a specific version will have to install the one that is used by the CI

**Comment by jonesmz** [comment]
My recommendation is for now to install clang 18 on the CI by adding the new apt sources to the runner before asking it to install the clang-format-18 package.

I think going forward though, we can permanently fix the issue by having a post-merge action that automatically runs clang format and submits an auto format commit.

**Comment by eakraly** [comment]
Leaving for later
Now I have easier solution to install clang-format 15 locally

**Pull request merged**
