### PR TITLE
Print full date and time in logs

### PR DESCRIPTION
**Pull request by PaulWay**
The 'number of seconds since the daemon was started' is amusing and compact, but it hinders debugging and correlation with other events.  This implements logs that use a complete `YYYY-MM-DDTHH:MM:SS` output which is easy to read and correlate.

Signed-off-by: Paul Wayper <paulway@mabula.net>

### CODE REVIEW

**Comment by PaulWay** [comment]
Haven't checked if this compiles or not yet, and haven't removed the old `log_start_time` and `log_time()` code.

One possibility I though of was implementing this as an option that could be turned on or off, say by a command-line or configuration option.  Haven't investigated how to do that yet.

**Comment by misi** [comment]
Please add flag / config option for that to avoid breaking changes

**Comment by PaulWay** [comment]
OK - do you want a flag to turn on the new log format, or a flag to turn on the old log format?  I.e. which log format should be the preferred?  I'm curious to know what value you see in the old format?

I'm happy to avoid a 'breaking' change in a significant feature or piece of functionality, but I'm not sure I see the utility of the old functionality.  I suppose I see it as a bug to be fixed rather than a feature that needs to be preserved.  Help me understand the significance of the old relative timestamp.

**Comment by PaulWay** [comment]
And would you prefer that flag, e.g. `int use_new_log_timestamp format`, to be in `apps/common/ns_turn_utils.h` or somewhere else?

**Comment by PaulWay** [comment]
This whole log printing is really puzzling me.

There's two separate places which format log lines.  One is in `turn_log_func_default`, which then calls the other in `vrtpprintf`.  This seems to do the whole process of reading the varargs and formatting the log line twice, before printing it to different locations (stdout in `turn_log_func_default`, syslog or the log file in `vrtpprintf`).  This seems to waste time doing the same job twice.

Is there a particular reason it's done this way?

What I'd propose to do here is to format the log line once and then print that to stdout, the log file and syslog as required by the relevant flags.  This would all be handled in the one function `turn_log_func_default`, with the `vrtpprintf` function being effectively folded into it.  One buffer would be allocated to format the log line, and this would reduce the code size and give more consistency.

But I won't go ahead with that if there's strong opposition to it, or if there's a particular reason for doing it the current way which I don't understand.  So please let me know what you'd prefer me to do here.

**Comment by PaulWay** [comment]
So I've merged the log printing into one function, and allowed users to set the timestamp as well.  Still trying to test the code to see if it actually works.

**Comment by PaulWay** [comment]
@misi Any thoughts?

**Comment by misi** [comment]
@PaulWay  Sorry for my late reply!
> OK - do you want a flag to turn on the new log format, or a flag to turn on the old log format? I.e. which log format should be the preferred? I'm curious to know what value you see in the old format?

I want a flag for the new to be backward compatible.
> 
> I'm happy to avoid a 'breaking' change in a significant feature or piece of functionality, but I'm not sure I see the utility of the old functionality. I suppose I see it as a bug to be fixed rather than a feature that needs to be preserved. Help me understand the significance of the old relative timestamp.

I believe we need smooth transition. It could be someone built systems on it, so I propose to have new flag and indicate in the docs that it will flipped in the next version and your will be the default, and after one version iteration the default behavior will change to the new, to give time to prepare for the change.

**Comment by misi** [comment]
> This whole log printing is really puzzling me.
> 
> There's two separate places which format log lines. One is in `turn_log_func_default`, which then calls the other in `vrtpprintf`. This seems to do the whole process of reading the varargs and formatting the log line twice, before printing it to different locations (stdout in `turn_log_func_default`, syslog or the log file in `vrtpprintf`). This seems to waste time doing the same job twice.
> 
> Is there a particular reason it's done this way?
> 
> What I'd propose to do here is to format the log line once and then print that to stdout, the log file and syslog as required by the relevant flags. This would all be handled in the one function `turn_log_func_default`, with the `vrtpprintf` function being effectively folded into it. One buffer would be allocated to format the log line, and this would reduce the code size and give more consistency.
> 
> But I won't go ahead with that if there's strong opposition to it, or if there's a particular reason for doing it the current way which I don't understand. So please let me know what you'd prefer me to do here.

Unfortunately I am not the original author of the code, so I can't help in it why it was designed that way. We can simplify, but need to be backward compatible and not break any usage. So let's make it in a different PR..

**Comment by misi** [comment]
> @misi Any thoughts?
@PaulWay 
Sorry I have limited time.. :-(
Accept my apologies that I can only reach here now..

**Comment by misi** [comment]
We need to also think that wide OS supported so it should work and compatible with more exotic OSs like mac, win, etc.

**Comment by PaulWay** [comment]
Hi @misi - thanks for that, sorry for not getting back to you earlier.  Hope this all works well!

**Comment by misi** [comment]
@PaulWay I adjusted little bit (add doc, fix cli etc.) but it seems working fine now. Thanks for your help and contribution!

**Pull request merged**
