### PR TITLE
MSVC support

### PR DESCRIPTION
**Pull request by SamuelMarks**
You've had a long-running note in your TODO file since at least 2014.

This PR aims to make coturn build [without error] on MSVC using CMake.

Future PRs can add native GUI and whatever else you had in mind.

Would welcome input

### CODE REVIEW

**Review by KangLin — COMMENTED** [review]
merge into #719

**Review by KangLin — COMMENTED** [review]
merge into https://github.com/KangLin/coturn/tree/windows

**Comment by SamuelMarks** [comment]
@KangLin I'm confused. Want me to just add you to my fork with full access to commit to any branch on my repo?

**Comment by KangLin** [comment]
I just want to explain, I reviewed this submission, and the content of this submission has been added to my submission. 😄

**Comment by SamuelMarks** [comment]
Wait but my commits aren't in your https://github.com/coturn/coturn/pull/719/commits

**Comment by Neustradamus** [comment]
@misi: Happy New Year 2022!

Can you look the @SamuelMarks PR?

Thanks in advance.

**Comment by ggarber** [comment]
@SamuelMarks Can you clarify if this is still needed or the effort is done now in #855 ?  If that's the case can you close this PR?  Thank you very much for all the work put on this feature.

**Comment by ggarber** [comment]
Included in #855

**Comment by Neustradamus** [comment]
It has been merged here, good job from @KangLin!
- https://github.com/coturn/coturn/pull/855

**Pull request closed without merging**
