### PR TITLE
fix memory leak of turn_session

### PR DESCRIPTION
**Pull request by huhaipeng**
fix bug mentioned in issue #950

### CODE REVIEW

**Comment by eakraly** [comment]
Thanks @huhaipeng !

I have not tested it myself - could you please provide more detailed description of what objects are leaking, and how your fix addresses that?
Also, if you did some tests or even long running tests - what results did you see?

Thank you! (just trying to make sure we document enough information about the bugs and fixes so that it is easier to understand why those changes were done and how they fix the issues without the need to dive deep into the code)

**Comment by huhaipeng** [comment]
> 

Actually, as below, before fixing, the session_map may be larger and larger when register_callback_on_ioa_socket inside open_client_connection_session retrun -1. The reason is that, if register_callback_on_ioa_socket return -1, no read/write/ event will be registered and no timeout event will be registered, in this case, the session will never be deleted from session_map.
image

After fixing, if open_client_connection_session return -1, shutdown_client_connection will be called, the session created from open_client_connection_session will be deleted and free in shutdown_client_connection.
@eakraly @ggarber

**Comment by huhaipeng** [comment]
I haven't writed any unit tests. But I have applied my fix version in my test envrinment, it seems work correctly
@eakraly @ggarber

**Comment by huhaipeng** [comment]
I found a better way to resolve this bug, close this PR.

**Pull request closed without merging**
