### PR TITLE
Avoid to expand docker arguments in docker-entrypoint.sh

### PR DESCRIPTION
**Pull request by shu-mutou**
Not to expand arguments and to able to use `--mysql-userdb` in docker, simply use `exec "$@"` instead `exec $(eval "echo $@")`.

Fixes: #902

### CODE REVIEW

**Comment by shu-mutou** [comment]
https://github.com/coturn/coturn/commit/d1b7acb0a52e8b6fa2fd74e4b474cbc8f0566f01 fixes only commit message, thanks in advance!

**Review by tyranron — CHANGES_REQUESTED** [review]
@shu-mutou expanding arguments was done not just out of a random, but on purpose: allow using `$(detect-external-ip)` as a command argument (examples are given in README).

We couldn't just remove this feature. Either it should be preserved or an alternative proposed.

Regarding #902: wouldn't single quotes `'` resolve the issue like this `--min-port=49160 --max-port=49200 -e --psql-userdb='host=192.168.31.173 port=5432 dbname=webrtc connect_timeout=10'`?

**Comment by shu-mutou** [comment]
To use it from shell script for CD , I also use envs in `--mysqldb-userdb` like `--mysqldb-userdb="host=${MYSQL_HOST} dbname=${MYSQL_DBNAME} user=${MYSQL_USER} password=${MYSQL_PASS} port=${MYSQL_PORT}"`.
So current implement is over expanding for me. 

What about adding envs to run `detect-external-ip` like `DETECT_EXTERNAL_IP` and `DETECT_EXTERNAL_IPV6`.

I'll investigate, so please wait for a while.

**Comment by shu-mutou** [comment]
`$(eval "echo $@")` seems to expand sigle quote `'` too....

**Comment by shu-mutou** [comment]
@tyranron PTAL again.

**Comment by eakraly** [comment]
I feel like we are adding inconsistency: we can pass multiple arguments in command line, but those 4 specific are through environment variables.
What about using arguments instead (something like --detect-external-ip) which will signal the entrypoint to do exactly the same?

**Comment by tyranron** [comment]
> To use it from shell script for CD , I also use envs in `--mysqldb-userdb` like `--mysqldb-userdb="host=${MYSQL_HOST} dbname=${MYSQL_DBNAME} user=${MYSQL_USER} password=${MYSQL_PASS} port=${MYSQL_PORT}"`. So current implement is over expanding for me.

@shu-mutou could you specify the whole command you're using, so I can tackle with it and try to think of the solution?

**Comment by shu-mutou** [comment]
@tyranron 

I tried following command.

```
docker run coturn/coturn --mysqldb-userdb='host=192.168.1.100 dbname=coturn user=coturn' -V
```

Then, it returns following message at first.

```
turnserver: unrecognized option '--mysqldb-userdb=host=192.168.1.100'
```

Thanks!

**Comment by shu-mutou** [comment]
@eakraly 

> What about using arguments instead (something like --detect-external-ip) which will signal the entrypoint to do exactly the same?

It sounds good! But it's been 20 years since I used C, and I've forgotten it.... sorry.

**Comment by eakraly** [comment]
> @eakraly
> 
> > What about using arguments instead (something like --detect-external-ip) which will signal the entrypoint to do exactly the same?
> 
> It sounds good! But it's been 20 years since I used C, and I've forgotten it.... sorry.

Oh - it has nothing to do with C actually
What I meant is that entrypoint.sh would accept those as arguments instead of env variables.
You pass them to executable as arguments anyway

We are talking about `getopt` https://stackabuse.com/how-to-parse-command-line-arguments-in-bash/
```
if [ -v DETECT_EXTERNAL_IP ]; then <=== Replace this
  DETECT_EXTERNAL_IP=" --external-ip=$(eval "detect-external-ip")"
fi
```

**Comment by shu-mutou** [comment]
@eakraly, thank you for reply!

I think it is better to explicitly separate the usage of coturn command options and docker image options.
Some people may be using coturn binary directly instead of docker, so I think it will cause confusion.

Your solution requires parsing and editing all of the arguments, including options for coturn, and I'm afraid that implementation will cause further problems.

**Review by tyranron — APPROVED** [review]
@shu-mutou sorry for replying late on this.

I've considered your examples and played around quite a while to come up with a solution. For all the tests I did, it expands correctly now. Hope, this will fix your issue too.

Thanks for bringing this up.

**Comment by tyranron** [comment]
@shu-mutou released in [4.6.1-r1](https://github.com/coturn/coturn/releases/tag/docker%2F4.6.1-r1).

**Comment by shu-mutou** [comment]
@tyranron Thank you so much for checking and merging this! :heart:

**Pull request merged**
