### PR TITLE
support of --acme-redirect <URL>

### LINKED ISSUE #546: Allow ACME redirects
Would be nice, if coturn would support redirecting ACME requests. E.g. if one has configured 
`acme-redirect = "http://le.example.com/.well-known/acme-challenge/"`

E.g. any request like this:
```
printf 'GET /.well-known/acme-challenge/0zXRO6tN1ijjwJD9QbDLldLwg-XrYoqz1QRSV6zfLSs HTTP/1.1\r\n
Host: stun.example.com\r\n
User-Agent: Mozilla/5.0 (compatible; Let'"'"'s Encrypt validation server; +https://www.letsencrypt.org)\r\n
Accept: */*\r\n
Accept-Encoding: gzip\r\n
\r\n' | netcat stun.example.com 80
``` 
should return a response like this and close the connection:
```
HTTP/1.1 301 Moved Permanently\r\n
Content-Type: text/html\r
Content-Length: 179\r\n
Connection: close\r\n
Location: http://le.example.com/.well-known/acme-challenge/0zXRO6tN1ijjwJD9QbDLldLwg-XrYoqz1QRSV6zfLSs\r\n
\r\n
<html><head><title>301 Moved Permanently</title></head>\r\n
<body><h1>301 Moved Permanently</h1></body>\r\n
</html>
```

### PR DESCRIPTION
**Pull request by jelmd**
fix #546

### CODE REVIEW

**Comment by misi** [comment]
@jelmd I need to review more so not in 4.5.1.3 but after the next version I will review and merge it. Many Thanks!

**Comment by misi** [comment]
I started to review it.

I* t is not connected to http admin server so it is maybe misleading to include in http_server, 
so we should separate your new code from it.
* And there is this plan A and B that need to be clean up.

Thanks for your cooperation and help!

**Comment by jelmd** [comment]
>     * It is not connected to http admin server so it is maybe misleading to include in http_server,
>       so we should separate your new code from it.

Feel free to move it to the location, where it fits best. Just thought, this is plain http stuff and similar to what is in http_server, so move it there to not clutter ns_turn_server.c  too much.

>     * And there is this plan A and B that need to be clean up.

Yepp, A is the workaround I found, which seems to be used by other SW as well having the same problem. Perhaps it is a common libevent [usage] problem?

**Comment by misi** [comment]
@jemld
I made something. Little bit adjusted here and there. 
Check out branch: https://github.com/coturn/coturn/tree/acme

It seems working..but it needed to be tested. 
(Unfortunately I will be unavailable for 2 weeks. :-/)

**Comment by jelmd** [comment]
Just checked. Does not work. However, if I enable variant A, it works.

For testing just add something like `acme-redirect = "http://foobar.do.main/.well-known/acme-challenge/"` to your `turnserver.conf` and run
```
printf 'GET /.well-known/acme-challenge/0zXRO6tN1ijjwJD9QbDLldLwg-XrYoqz1QRSV6zfLSs HTTP/1.1\r\nHost: stun.example.com\r\nUser-Agent: Mozilla/5.0 (compatible; Let'"'"'s Encrypt validation server; +https://www.letsencrypt.org)\r\nAccept: */*\r\nAccept-Encoding: gzip\r\n\r\n' |netcat  stun,.do.main ${STUNPORT}
```

Set STUNPORT to the `listening-port` of your stun instance. When running the command, it should print out something starting with `HTTP/1.1 301 Moved Permanently`. If it doesn't, it does not work.

**Comment by Neustradamus** [comment]
@misi: Have you seen?

**Comment by misi** [comment]
@jelmd please test it. For me it worked fine I could renew cert with certbot..

**Comment by jelmd** [comment]
> @jelmd please test it. For me it worked fine I could renew cert with certbot..

Well, just merging it as it shouldn't produce any different results, but I'll take the time to test again.

NOTE: Running certbot is not a valid test: Either certbot listens on port 80 and thus coturn not, or vice versa. Also there are a lot of different ways certbot may use to obtain a cert, so I'm not convinced by "certbot works for me". The correct test is the one I've shown above, having coturn listen on the corresponding port.

**Comment by misi** [comment]
@jelmd  I am so sorry for my brevity. I tested certbot  that way that with DNAT port forwarded from tcp port 80 to coturn 3478 port
(so it is like coturn listening on port 80) and coturn because of the  acme redirect redirected to other ip 443 where certbot listened, and it was successful.

I have also tested according your description and it works also that way as it should. 

I am extremely sorry for the delayed merge, 
and  I warmly welcome anyone to join me and help maintaining coturn. 
Unfortunately I am very alone with limited time..

```
misi@coturn-test:~/coturn$ printf 'GET /.well-known/acme-challenge/0zXRO6tN1ijjwJD9QbDLldLwg-XrYoqz1QRSV6zfLSs HTTP/1.1\r\nHost: stun.example.com\r\nUser-Agent: Mozilla/5.0 (compatible; Let'"'"'s Encrypt validation server; +https://www.letsencrypt.org)\r\nAccept: */*\r\nAccept-Encoding: gzip\r\n\r\n' |netcat  localhost 3478
HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Content-Length: 107
Connection: close
Location: http://coturn-test.lab.vvc.niif.hu:443/.well-known/acme-challenge/0zXRO6tN1ijjwJD9QbDLldLwg-XrYoqz1QRSV6zfLSs

<html><head><title>301 Moved Permanently</title></head>		<body><h1>301 Moved Permanently</h1></body></html>

```

**Comment by jelmd** [comment]
Hmmm, just tried the master branch @ 8dc5bbc - unfortunately it does not work on Ubuntu 20.04 latest.
Is your turnserver running within a container?

**Pull request merged**
