### PR TITLE
SSL reload has hidden bugs which cause crashes

### PR DESCRIPTION
**Pull request by hills**
The process  would run for a while, but eventually crash. valgrind shows a bug immediately, but memory (re-)use means that actual effect can be mostly invisible (tested on musl libc).

Each patch explains. We've been running these patches for a while now, but I just rebased them to the most recent coturn.

### CODE REVIEW

**Comment by misi** [comment]
Many Thanks! I need some time to understand the changes! Thanks for your patience..

**Comment by argggh** [comment]
As chance would have it, we have also been seeing this in the wild in the last 24 hours. FWIW, the change looks reasonable to me. (I was probably  the one who introduced this as well way back when... :disappointed:)

**Comment by hills** [comment]
Any movement on these patches? I would not want them to get out of date by some change on the main branch.

**Comment by misi** [comment]
@hills I will merge it ASAP..

**Pull request merged**
