### PR TITLE
Fix user quota release #786

### PR DESCRIPTION
**Pull request by yfaker**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@misi: Happy New Year 2022!

Can you look the @yfaker PR?

Thanks in advance.

**Comment by Neustradamus** [comment]
@ggarber: Can you look?

**Comment by eakraly** [comment]
Following this as well
This is also a memory leak if I read this correctly

**Comment by ggarber** [comment]
Yep, Looks like a bug but I'm not sure of the side effects of this change yet.    Are we sure nobody will read from that map after that point in the code?  Is this the only/best place where we need to do the `ur_string_map_del` ?

I will try to take a look at those things asap.  If @yfaker have any input on those things that will be also helpful.

**Pull request merged**
