### PR TITLE
Add clang format rules and checks

### PR DESCRIPTION
**Pull request by ggarber**
I would like to get feedback on this and see if people is confortable with these clang rules.

Right now is using the "llvm" style increasing the line length from 80 to 120 given that coturn is using long lines often.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@ggarber: Please look all other PRs before

**Comment by eakraly** [comment]
Love auto-formatting, not even important the details.

**Comment by eakraly** [comment]
@Neustradamus Do you mean that we should merge other PRs before we merge this formatting change? I doubt we ever get to a time when we have 0 PRs...

**Review by eakraly — APPROVED** [review]
I do not mind any format as long as it is auto-formatted
Would love to see it merged asap (understanding that outstanding PRs will need some rework)

**Comment by Neustradamus** [comment]
@eakraly: Cleaning has been done but there are always some PRs here:
- https://github.com/coturn/coturn/pulls

Clang will change files...

**Pull request merged**
