### PR TITLE
Move web-admin interface to dedicated (and configurable) ip:port

### PR DESCRIPTION
**Pull request by thib-ack**
Hello,

I've moved the https web-admin interface to a dedicated ip:port, rather than the standard STUN ports. I added 3 new options to configure this:
`--no-web-admin (default: web-admin is enabled)`
`--web-admin-ip=<IP> (default: 127.0.0.1)`
`--web-admin-port=<port> (default: 8080)`

Thanks for reviewing & hope it will help.
Thibaut.

### CODE REVIEW

**Comment by misi** [comment]
I am working on merge this commit.

**Comment by dimidiam** [comment]
Any update on this?

**Comment by misi** [comment]
@dimidiam I still ask your patience. . 
I want to test first the actual master branch and roll it out as a new release.
After releasing actual changes I will add these fix bundled with other fixes.
Please help me to test the actual master branch and give feedback..
Test the new features. e.g. Cert reload etc..

**Comment by misi** [comment]
I made a hidden merge to my working branch. So it is in the pipe, but first I have to focus on testing and releasing the actual changes.

**Comment by misi** [comment]
It will be in release Nov 1

**Comment by thib-ack** [comment]
Hello,

I know you are working on this and maybe you have even re-wrote most of it, but I found a memory leak in my initial commit so I've submitted a bugfix.

I still hope it will help and hope you review all of this because I have to admit a still not 100% sure of my patch ;-)

Thanks
Thibaut.

**Comment by misi** [comment]
Many Thanks!
 I will check it..

**Comment by ni3ls** [comment]
Hi,
any news on this feature?
I really need this for production as soon as possible.
I tried to apply the suggested patch to current version 4.5.0.8 and recompile but it fails with an error:

src/apps/relay/turn_admin_server.c:1308:3: warning: nested extern declaration of ‘set_ssl_ctx’ [-Wnested-externs]
/tmp/ccTbOgQG.o: In function `setup_admin_thread':
/home/ubuntu/coturn/src/apps/relay/turn_admin_server.c:1308: undefined reference to `set_ssl_ctx'
collect2: error: ld returned 1 exit status
Makefile:134: recipe for target 'bin/turnserver' failed
make: *** [bin/turnserver] Error 1

It seems like the use of the function set_ssl_ctx in the file is not allowed? Also this function does not seem to be declared externally (no src/apps/relay/netengine.h file exist with this function which is implemented in the src/apps/relay/netengine.c file) ?

Any suggestions on how to fix this while we wait for the conflicts to be resolved?

Thank you so much in advance.

/Niels

**Comment by misi** [comment]
This branch is incorporated in 4.5.1.0
Many Thanks for it.

**Pull request merged**
