### PR TITLE
upgrade docker alpine image to alpine 3.17

### PR DESCRIPTION
**Pull request by Zoey2936**
I've tried building it with this change, and it worked without problem (required for https://github.com/nextcloud/all-in-one/pull/1583)

### CODE REVIEW

**Comment by eakraly** [comment]
Summoning @tyranron to weigh in
Unblocking review and builds for now

**Comment by Zoey2936** [comment]
Thanks!

**Comment by tyranron** [comment]
@Zoey2936 @eakraly I've already tried it before, it works OK for `master` branch, but doesn't build with 4.6.1 Coturn release, due to its issues with OpenSSL 3.x.

You may check this by trying `make image dockerfile=alpine ref=4.6.1` command in `docker/coturn/` dir.

We're blocked with Alpine 3.17 until `master` with fixed support of OpenSSL 3.x is released.

**Comment by Zoey2936** [comment]
> You may check this by trying `make image dockerfile=alpine ref=4.6.1` command in `docker/coturn/` dir.

I see...

**Comment by eakraly** [comment]
@tyranron can we submit this change based on 4.6.1-r2 since it is tagged off latest master?

**Comment by tyranron** [comment]
@eakraly no. Despite it's tagged off latest `master`, it uses `4.6.1` Git tag to build Docker image from. We cannot have 3.17 unless we release latest `master` as new Coturn version.

**Comment by eakraly** [comment]
@ggarber Why don't we make 4.6.2 release then? 4.6.1 is broken wrt openssl-3.0...

**Comment by Zoey2936** [comment]
> @ggarber Why don't we make 4.6.2 release then? 4.6.1 is broken wrt openssl-3.0...

If this is possible, it would be great to see!

**Review by tyranron — APPROVED** [review]

**Comment by tyranron** [comment]
@Zoey2936 @eakraly released in [4.6.2-r0](https://github.com/coturn/coturn/releases/tag/docker%2F4.6.2-r0).

**Comment by Zoey2936** [comment]
thanks!

**Pull request merged**
