### PR TITLE
RFC 5928 in good part

### PR DESCRIPTION
**Pull request by Neustradamus**
RFC 5928 in good part

### CODE REVIEW

**Comment by misi** [comment]
@Neustradamus 
This RFC is about dns resolution for clients. 

- The server supports clients with such SRV based resolution for sure.
 
- Or you mean we should support in the test uclient this functionality?
  Coturn is a server has only a basic test client.

**Comment by misi** [comment]
So I would like to leave it as it is actually. 
Maybe we should open an issue to support RFC5928 in uclient. What do you think?

**Comment by Neustradamus** [comment]
@misi: The "RFC5928: Traversal Using Relays around NAT (TURN) Resolution Mechanism" is linked to TURN

**Comment by misi** [comment]
@Neustradamus  
Sorry I do not understand your point. AFAIU  RFC 5928 is  about TURN client NAPTR resolution. The coTURN project is about the server side.  
Can you point me which part of the RFC 5928 needs any change on the actual server behavior? Thanks!

**Comment by Neustradamus** [comment]
@misi: In the README file:

Supported RFCs:

TURN specs:

    RFC 5766 - base TURN specs
    RFC 6062 - TCP relaying TURN extension
    RFC 6156 - IPv6 extension for TURN
    RFC 7443 - ALPN support for STUN & TURN
    RFC 7635 - oAuth third-party TURN/STUN authorization
    DTLS support (http://tools.ietf.org/html/draft-petithuguenin-tram-turn-dtls-00).
    Mobile ICE (MICE) support (http://tools.ietf.org/html/draft-wing-tram-turn-mobility-02).
    TURN REST API (http://tools.ietf.org/html/draft-uberti-behave-turn-rest-00)
    Origin field in TURN (Multi-tenant TURN Server) (https://tools.ietf.org/html/draft-ietf-tram-stun-origin-06)
    TURN Bandwidth draft specs (http://tools.ietf.org/html/draft-thomson-tram-turn-bandwidth-01)
    TURN-bis (with dual allocation) draft specs (http://tools.ietf.org/html/draft-ietf-tram-turnbis-04).

STUN specs:

    RFC 3489 - "classic" STUN
    RFC 5389 - base "new" STUN specs
    RFC 5769 - test vectors for STUN protocol testing
    RFC 5780 - NAT behavior discovery support
    RFC 7443 - ALPN support for STUN & TURN
    RFC 7635 - oAuth third-party TURN/STUN authorization

Supported ICE and related specs:

    RFC 5245 - ICE
    RFC 5768 – ICE–SIP
    RFC 6336 – ICE–IANA Registry
    RFC 6544 – ICE–TCP
    RFC 5928 - TURN Resolution Mechanism


"RFC 5928 - TURN Resolution Mechanism" is not in TURN part.

My PR solves it

**Comment by misi** [comment]
Thanks & Sorry I totally misunderstood your PR.  

Now I see what you mean. 
I fully understand why Oleg put this RFC to ICE related RFCs and I tend to agree with him, because this RFC is more about on client resolution, so more related to TURN Client and ICE part. 
Do you mind if we leave it there where it is? 
I fully understand your point that it is TURN but not really about TURN server related RFCs, but more on client side, even more it is somehow preliminary TURN server discovery using DNS, so not related about the core TURN server RFCs.

**Comment by misi** [comment]
I concluded to keep it as is. Sorry, I hope you understand why it is related RFC..

**Pull request closed without merging**
