### PR TITLE
Do not use FIPS and remove hardcode OPENSSL_VERSION_NUMBER with LibreSSL

### LINKED ISSUE #552: LibreSSL compilation failures
Compilation with a current version of LibreSSL produces an error and a warning:

- [LibreSSL has no FIPS mode](https://marc.info/?l=openbsd-misc&m=139819485423701) so `FIPS_mode()` is not defined:
https://github.com/coturn/coturn/blob/113f13855a53aeb41ca5b71aa36b3f945cee2052/src/client/ns_turn_msg.c#L247-L249
https://github.com/coturn/coturn/blob/113f13855a53aeb41ca5b71aa36b3f945cee2052/src/client/ns_turn_msg.c#L257-L259

  A potential fix is to enclose both calls with `#ifdef OPENSSL_FIPS ... #endif` which was removed in https://github.com/coturn/coturn/commit/0e03fa86df3c2ba3afb3793c724d3579afd1ecf3 .

- Hardcoding an old OpenSSL version number if LibreSSL is detected
https://github.com/coturn/coturn/blob/113f13855a53aeb41ca5b71aa36b3f945cee2052/src/apps/common/ns_turn_openssl.h#L45-L48
causes a problem when compiling
https://github.com/coturn/coturn/blob/113f13855a53aeb41ca5b71aa36b3f945cee2052/src/apps/relay/dtls_listener.c#L209-L211 as newer LibreSSL versions need the `const` modifier.

  To address this either revisit the mapping of LibreSSL to an old OpenSSL version number or use an explicit `| defined(LIBRESSL_VERSION_NUMBER)` here.

### PR DESCRIPTION
**Pull request by cedk**
Fix #552

### CODE REVIEW

**Comment by Neustradamus** [comment]
@misi: Have you seen?

**Comment by misi** [comment]
@cedk  Do you think removing this default ssl version value will not cause any issue? I guess the reason it was there somehow to fallback if it is not configured. What do you think?

**Comment by cedk** [comment]
For me it prevents to use other feature of libressl to hard code its openssl version.
It is better to not use a feature based on the version of the library than pretending that a library has a different version.
As far as I have seen other codes use similar test when dealing with openssl and libressl compatibility.

**Comment by misi** [comment]
I am not expert on this field, so I hope it will not make any trouble.. :)
Thanks for your contribution!

**Comment by Neustradamus** [comment]
@misi: Thanks for merging of several PRs.

Please look other current PRs, last comments/changes and please do a new comment if it is not good...

**Comment by misi** [comment]
@Neustradamus I do my best as always. :-)

**Pull request merged**
